//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HermesLicencingInterface.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LicencingDBEntities : DbContext
    {
        public LicencingDBEntities()
            : base("name=LicencingDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TEmpresa> TEmpresa { get; set; }
        public DbSet<TLicenca> TLicenca { get; set; }
        public DbSet<TUtilizador> TUtilizador { get; set; }
    }
}
