//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HermesLicencingInterface.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class TLicenca
    {
        public int idLicenca { get; set; }
        public string imei { get; set; }
        public int idEmpresa { get; set; }
        public string estado { get; set; }
        public string codLicenca { get; set; }

        public virtual TEmpresa TEmpresa { get; set; }

        public static List<TLicenca> All()
        {
            var db = new Models.LicencingDBEntities();

            var query = db.TLicenca.Select(c => c);
            return query.ToList();
        }

        public static TLicenca GetById(int id)
        {

            var db = new Models.LicencingDBEntities();

            var query = db.TLicenca.Where(c => c.idLicenca == id).Select(c => c);
            return query.ToList().First();
        }

        public static TLicenca GetByIMEI(string imei)
        {

            var db = new Models.LicencingDBEntities();

            var query = db.TLicenca.Where(c => c.imei == imei).Select(c => c);
            return query.ToList().First();
        }

        public static List<TLicenca> GetByEmp(int idEmp)
        {

            var db = new Models.LicencingDBEntities();

            var query = db.TLicenca.Where(c => c.idEmpresa == idEmp).Select(c => c);
            return query.ToList();
        }

        public static int Update(TLicenca lic)
        {
            int ret = 0;
            var db = new Models.LicencingDBEntities();

            var query = db.TLicenca.Select(c => c);
            var licencas = query.ToList();

            if (!ValidateData(lic))
                return 2;

            foreach (TLicenca l in licencas)
            {
                if (lic.idLicenca == l.idLicenca)
                {
                    l.idLicenca = lic.idLicenca;
                    l.imei = lic.imei;
                    l.estado = lic.estado;
                    l.idEmpresa = lic.idEmpresa;
                    l.codLicenca = lic.codLicenca;

                    db.SaveChanges();
                    ret = 1;
                    break;
                }
            }
            return ret;
        }

        public static int AddLicenca(TLicenca lic)
        {
            var db = new Models.LicencingDBEntities();

            if (!ValidateData(lic))
                return 2;

            //gerar código único para empresa
            lic.codLicenca = "" + (lic.idLicenca + 1000);

            db.TLicenca.Add(lic);
            db.SaveChanges();

            return lic.idLicenca;
        }

        public static bool ValidateData(TLicenca lic)
        {
            bool ret = true;

            if (lic.idLicenca == null)
                return false;
            if (lic.imei == null)
                return false;
            if (lic.estado == null)
                return false;
            if (lic.idEmpresa == null)
                return false;
            if (lic.codLicenca == null)
                return false;

            return ret;
        }
    }
}
