//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HermesLicencingInterface.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class TLicenca
    {
        public int idLicenca { get; set; }
        public string imei { get; set; }
        public int idEmpresa { get; set; }
        public string estado { get; set; }
        public string codLicenca { get; set; }

        public virtual TEmpresa TEmpresa { get; set; }

        public static List<TLicenca> All()
        {
            List<TLicenca> ret;

            var db = new Models.LicencingDBEntities();

            var query = db.TLicenca.Select(c => c);

            ret = query.ToList();
            if (ret.Count > 0)
                return ret;

            return new List<TLicenca>();
        }

        public static TLicenca GetById(int id)
        {
            var db = new Models.LicencingDBEntities();

            var query = db.TLicenca.Where(c => c.idLicenca == id).Select(c => c);

            var list = query.ToList();
            if (list.Count > 0)
                return query.ToList().First();

            return null;
        }

        public static TLicenca GetByIMEI(string imei)
        {
            var db = new Models.LicencingDBEntities();

            var query = db.TLicenca.Where(x => x.imei.Equals(imei));

            var list = query.ToList();
            if (list.Count > 0)
                return query.ToList().First();

            return null;
        }

        public static List<TLicenca> GetByEmp(int idEmp)
        {
            List<TLicenca> ret;

            var db = new Models.LicencingDBEntities();

            var query = db.TLicenca.Where(c => c.idEmpresa == idEmp).Select(c => c);

            ret = query.ToList();
            if (ret.Count > 0)
                return ret;

            return new List<TLicenca>();


        }

        public static int Update(TLicenca lic)
        {
            int ret = 0;
            var db = new Models.LicencingDBEntities();

            var query = db.TLicenca.Select(c => c);
            var licencas = query.ToList();

            if (!ValidateData(lic))
                return 2;

            foreach (TLicenca l in licencas)
            {
                if (lic.idLicenca == l.idLicenca)
                {
                    l.idLicenca = lic.idLicenca;
                    l.imei = lic.imei;
                    l.estado = lic.estado;
                    l.idEmpresa = lic.idEmpresa;
                    l.codLicenca = lic.codLicenca;

                    db.SaveChanges();
                    ret = 1;
                    break;
                }
            }
            return ret;
        }

        public static int AddLicenca(TLicenca lic)
        {
            var db = new Models.LicencingDBEntities();

            //gerar código único para empresa
            lic.codLicenca = "" + (lic.idLicenca + 1000);

            db.TLicenca.Add(lic);
            db.SaveChanges();

            return lic.idLicenca;
        }

        public static int DeleteById(int id)
        {
            var db = new Models.LicencingDBEntities();
            int ret = 0;

            var query = db.TLicenca.Where(c => c.idLicenca == id).Select(c => c);

            var list = query.ToList();
            if (list.Count > 0)
            {
                db.TLicenca.Remove(query.ToList().First());
                db.SaveChanges();
                ret = 1;
            }


            return ret;
        }

        public static bool ValidateData(TLicenca lic)
        {
            bool ret = true;

            if (lic.idLicenca == null)
                return false;
            if (lic.imei == null)
                return false;
            if (lic.estado == null)
                return false;
            if (lic.idEmpresa == null)
                return false;
            if (lic.codLicenca == null)
                return false;

            return ret;
        }
    }
}
