//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HermesClient.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PESTICliEntities : DbContext
    {
        public PESTICliEntities()
            : base("name=PESTICliEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TCliente> TCliente { get; set; }
        public DbSet<TGuiaTransporte> TGuiaTransporte { get; set; }
        public DbSet<TLinhaProduto> TLinhaProduto { get; set; }
        public DbSet<TLocal> TLocal { get; set; }
        public DbSet<TProduto> TProduto { get; set; }
        public DbSet<TUtilizador> TUtilizador { get; set; }
        public DbSet<TEmpresa> TEmpresa { get; set; }
        public DbSet<TLicenca> TLicenca { get; set; }
    }
}
