//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a tclilate.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HermesClient.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.Web.Mvc;

    public partial class TCliente
    {
        public int idCliente { get; set; }

        [Required]
        [StringLength(200)]
        [Display(Name = "Nome: ")]
        public string nome { get; set; }

        [Required]
        [StringLength(9)]
        [Display(Name = "NIF: ")]
        public string nif { get; set; }

        [Required]
        [StringLength(15)]
        [Display(Name = "Contacto: ")]
        public string contacto { get; set; }


        public static List<TCliente> All()
        {
            var db = new Models.PESTICliEntities();

            var query = db.TCliente.Select(c => c);
            return query.ToList();
        }

        public static TCliente GetById(int id)
        {

            var db = new Models.PESTICliEntities();

            var query = db.TCliente.Where(c => c.idCliente == id).Select(c => c);
            return query.ToList().First();
        }

        public static int Update(TCliente cli)
        {
            int ret = 0;
            var db = new Models.PESTICliEntities();

            var query = db.TCliente.Select(c => c);
            var clis = query.ToList();

            if (!ValidateData(cli))
                return 2;

            foreach (TCliente c in clis)
            {
                if (cli.idCliente == c.idCliente)
                {
                    c.idCliente = cli.idCliente;
                    c.nome = cli.nome;
                    c.nif = cli.nif;
                    c.contacto = cli.contacto;

                    db.SaveChanges();
                    ret = 1;
                    break;
                }
            }
            return ret;
        }

        public static int AddCliente(TCliente cli)
        {
            var db = new Models.PESTICliEntities();

            if (!ValidateData(cli))
                return 2;

            db.TCliente.Add(cli);
            db.SaveChanges();

            return cli.idCliente;
        }

        public static bool ValidateData(TCliente cli)
        {
            bool ret = true;

            if (cli.nome == null && cli.nome.CompareTo("") == 0)
                return false;
            if (cli.nif == null && cli.nif.CompareTo("") == 0)
                return false;
            if (cli.contacto == null && cli.contacto.CompareTo("") == 0)
                return false;

            return ret;
        }
    }
}