//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HermesClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TGuiaTransporte
    {
        public TGuiaTransporte()
        {
            this.TLinhaProduto = new HashSet<TLinhaProduto>();
        }
    
        public int idGuia { get; set; }
        public Nullable<int> idEmissao { get; set; }
        public int idUtilizador { get; set; }
        public string matricula { get; set; }
        public int idCLiente { get; set; }
        public System.DateTime dataTransporte { get; set; }
        public int idLocalCarga { get; set; }
        public int idLocalDescarga { get; set; }
        public int estado { get; set; }
    
        public virtual TCliente TCliente { get; set; }
        public virtual TLocal TLocal { get; set; }
        public virtual TLocal TLocal1 { get; set; }
        public virtual ICollection<TLinhaProduto> TLinhaProduto { get; set; }
        public virtual TUtilizador TUtilizador { get; set; }
    }
}
