//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HermesClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TLinhaProduto
    {
        public int idGuia { get; set; }
        public int idProduto { get; set; }
        public int quantidade { get; set; }
    
        public virtual TProduto TProduto { get; set; }
    }
}
