//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HermesLicencing.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    
    public partial class TEmpresa
    {
        public int idEmpresa { get; set; }
        public string nome { get; set; }
        public string morada { get; set; }
        public string email { get; set; }
        public string nif { get; set; }
        public string contacto { get; set; }
        public string servidor { get; set; }
        public int idLicenca { get; set; }
    
        public virtual TLicenca TLicenca { get; set; }

        public static IEnumerable<TEmpresa> All()
        {
            var db = new Models.LicencingDBEntities();
            return db.Set<TEmpresa>();
        }

        public static TEmpresa GetById(int id)
        {

            var db = new Models.LicencingDBEntities();

            var query = db.TEmpresa.Where(c => c.idEmpresa == id).Select(c => c);
            return query.ToList().First();
        }
    }
}
