//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HermesLicencing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TLicenca
    {
        public int idLicenca { get; set; }
        public System.DateTime dataInicio { get; set; }
        public int idTipoLicenca { get; set; }
        public string estado { get; set; }
    
        public virtual TTipoLicenca TTipoLicenca { get; set; }
    }
}
