//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HermesLicencing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTipoLicenca
    {
        public int idTipoLicenca { get; set; }
        public string nome { get; set; }
        public string descricao { get; set; }
        public int duracao { get; set; }
        public decimal valor { get; set; }
    }
}
