//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HermesLicencing.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class TUtilizador
    {
        public int idUtilizador { get; set; }

        [Required]
        [StringLength(20)]
        [Display(Name = "Username: ")]
        public string username { get; set; }

        [Required]
        public string passwordSalt { get; set; }

        [Required]
        public string nome { get; set; }

        public int idEmpresa { get; set; }
        public int idTipoUtilizador { get; set; }

        [Required]
        public int estado { get; set; }

        [StringLength(20)]
        public string numSerieEquip { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [StringLength(200, MinimumLength = 6)]
        [Display(Name = "Password: ")]
        public string password { get; set; }

        [Required]
        [EmailAddress]
        [StringLength(100)]
        public string email { get; set; }


        public virtual TEmpresa TEmpresa { get; set; }
        public virtual TTipoUtilizador TTipoUtilizador { get; set; }

        public static IEnumerable<TUtilizador> All()
        {
            var db = new Models.LicencingDBEntities();
            return db.Set<TUtilizador>();
        }

        public static TUtilizador GetById(int id)
        {

            /*var db = new Models.LicencingDBEntities();
            return db.Set<TUtilizador>;*/
            return null;
        }
    }
}
